---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: ubuntu:18.04
    - MOLECULE_DISTRO: ubuntu:16.04

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  - cd ../ && mv ansible-polarproxy juju4.polarproxy
  - cd juju4.polarproxy

script:
  - molecule test

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
