---

- name: Ensure override folder exists
  ansible.builtin.file:
    dest: /etc/systemd/system/PolarProxy.service.d
    state: directory
    mode: '0755'

# if issue, check /var/log/audit/audit.log
- name: Review PolarProxy systemd options - RestartSec, Seccomp...
  ansible.builtin.template:
    src: systemd-override.conf.j2
    dest: /etc/systemd/system/PolarProxy.service.d/override.conf
    mode: '0644'
  notify:
    - reload systemd
    - restart PolarProxy
