---

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: restart rsyslog
  ansible.builtin.service: name=rsyslog state=restarted
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd") and
          (ansible_distribution == 'Alpine' or ansible_os_family == 'RedHat')
        )
