---

- name: reload systemd
  systemd:
    daemon_reload: true
  when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")

- name: restart rsyslog
  service: name=rsyslog state=restarted
  when: >
    not (ansible_virtualization_type is defined and
          ansible_virtualization_type == "docker" and
          (ansible_distribution == 'Alpine' or ansible_os_family == 'RedHat')
        )
