---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when:
    - not is_container|bool

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  when:
    - not is_container|bool
