---

- name: reload systemd
  systemd:
    daemon_reload: true
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "VirtualPC")
        )

- name: restart rsyslog
  service: name=rsyslog state=restarted
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "VirtualPC") and
          (ansible_distribution == 'Alpine' or ansible_os_family == 'RedHat')
        )
